# Generated by Django 4.1.2 on 2022-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QA_Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("par_A", models.TextField()),
                ("par_B", models.TextField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("comments", models.TextField()),
                ("featured", models.BooleanField(default=True)),
            ],
        ),
    ]
