# Generated by Django 4.1.2 on 2022-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qa_interface",
            name="answer",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="qa_interface",
            name="question",
            field=models.TextField(max_length=20),
        ),
    ]
