# Generated by Django 4.1.2 on 2022-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qa_interface",
            "0004_alter_qa_interface_answer_alter_qa_interface_par_a_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qa_interface",
            name="answer",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="qa_interface",
            name="par_A",
            field=models.TextField(
                default="Professor Victor J. Hruby is Regents Professor in the Department of Chemistry and Biochemistry at the University of Arizona. Dr. Hruby was born in Valley City, North Dakota and received his B.S. and M.S., with A. William Johnson, at the University of North Dakota. He then went to Cornell University where he received his Ph.D. with A. T. Blomquist"
            ),
        ),
        migrations.AlterField(
            model_name="qa_interface",
            name="par_B",
            field=models.TextField(
                default="He was an Instructor at Cornell University Medical College with Vincent duVigneaud, Nobel Laureate. He moved to the University of Arizona in 1968 as an Assistant Professor. He became Associate Professor with Tenure in 1972, Full Professor in 1977 and Regents Professor in 1989."
            ),
        ),
        migrations.AlterField(
            model_name="qa_interface",
            name="question",
            field=models.TextField(max_length=100),
        ),
    ]
