# Generated by Django 4.1.2 on 2022-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qa_interface",
            "0005_alter_qa_interface_answer_alter_qa_interface_par_a_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qa_interface",
            name="source_id",
            field=models.CharField(default="abc", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qa_interface",
            name="question",
            field=models.TextField(max_length=200),
        ),
    ]
