# Generated by Django 4.1.2 on 2022-11-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0008_alter_qa_interface_par_a_alter_qa_interface_par_b"),
    ]

    operations = [
        migrations.RemoveField(model_name="qa_interface", name="featured",),
    ]
