# Generated by Django 4.1.2 on 2022-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0009_remove_qa_interface_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qa_interface", name="par_A", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="qa_interface", name="par_B", field=models.TextField(),
        ),
    ]
