# Generated by Django 4.1.2 on 2022-12-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0010_alter_qa_interface_par_a_alter_qa_interface_par_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="qa_interface",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Bridge_entity", "Bridge"),
                    ("Comparison", "Comparison"),
                    ("Intersection", "Intersection"),
                    ("Commonsense_reasoning", "Commonsense"),
                ],
                default="Bridge_entity",
                max_length=22,
            ),
        ),
    ]
