# Generated by Django 4.1.2 on 2022-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0011_qa_interface_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="qa_interface",
            name="level",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Medium", "Medium"), ("Easy", "Easy")],
                default="Easy",
                max_length=6,
            ),
        ),
    ]
