# Generated by Django 4.1.2 on 2022-12-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0012_qa_interface_level"),
    ]

    operations = [
        migrations.RemoveField(model_name="qa_interface", name="source_id",),
    ]
