# Generated by Django 4.1.2 on 2022-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_interface", "0013_remove_qa_interface_source_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="qa_interface", name="comments",),
        migrations.AddField(
            model_name="qa_interface",
            name="supporting_facts",
            field=models.TextField(default=(0, 0), max_length=4),
            preserve_default=False,
        ),
    ]
