# Generated by Django 4.1.2 on 2023-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0014_remove_qa_interface_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='question',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='qa_interface',
            name='supporting_facts',
            field=models.TextField(help_text='Sentences that involves the multihop question from both the paragraphs..', max_length=4),
        ),
    ]
