# Generated by Django 4.1.2 on 2023-02-23 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0017_alter_qa_interface_supporting_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_interface',
            name='title_A',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qa_interface',
            name='title_B',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
