# Generated by Django 4.1.2 on 2023-02-23 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0022_alter_qa_interface_title_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_interface',
            name='source_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
