# Generated by Django 4.1.2 on 2023-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0023_qa_interface_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='supporting_facts',
            field=models.TextField(help_text=' &nbsp; <button type="button" class="btn btn-info" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-html="true" data-bs-content="Supporting facts indicates sentences involved while creating the multi hop question from both of the paragraphs.<br> Example Input: 0,1. It indicates first sentence from the first paragraph and second sentence from the second paragraph."> ? </button>', max_length=4),
        ),
    ]
