# Generated by Django 4.1.2 on 2023-02-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0024_alter_qa_interface_supporting_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], default='Easy', help_text=' &nbsp; <button type="button" class="btn btn-danger btn-sm align-top" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-html="true"  data-bs-content="Difficulty level of the multi hop question you entered! "> ? </button>', max_length=6),
        ),
        migrations.AlterField(
            model_name='qa_interface',
            name='question',
            field=models.TextField(help_text=' &nbsp; <button type="button" class="btn btn-danger btn-sm align-top" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-html="true"  data-bs-content=" Multi-hop questions require systems to aggregate information between multiple contexts, the ability of a system to reason over multiple sources of data such as paragraphs to output desired answer. Here, the system has to reason with information taken from more than one document (i.e. Parapgaphs) to arrive at the final answer. <br> <br> <b> Example: </b> What is the population of the capital city of Bangladesh ? <br> <b>Answer: </b> 40 Millions !!<br> <b>Reasoning:</b> Capital City of Bangladesh ---> Dhaka ---> Population: 40 Millions <br> <br> Click <a href= https://hotpotqa.github.io/  target=_blank > here </a> to see further details of multihop questions ! "> ? </button>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qa_interface',
            name='question_type',
            field=models.CharField(choices=[('Bridge_entity', 'Bridge'), ('Comparison', 'Comparison'), ('Intersection', 'Intersection'), ('Commonsense_reasoning', 'Commonsense')], default='Bridge_entity', help_text=' &nbsp; <button type="button" class="btn btn-danger btn-sm align-top" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-html="true"  data-bs-content=" Types of multi hop question you entered. Click <a href= https://github.com/UA-KMAP/KMAP-QA/blob/main/qa_interface/templates/images/MHQA.png  target=_blank> here </a> to see details of different types of multi hop question. "> ? </button>', max_length=22),
        ),
        migrations.AlterField(
            model_name='qa_interface',
            name='supporting_facts',
            field=models.TextField(help_text=' &nbsp; <button type="button" class="btn btn-danger btn-sm align-top" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-html="true"  data-bs-content="Supporting facts specify the sentences involved while creating the multi hop question from both of the paragraphs.<br> <b>Example Input: 0,1. </b> It indicates that first sentence from the first paragraph and second sentence from the second paragraph have been used to produce the multi hop question.."> ? </button>', max_length=4),
        ),
    ]
