# Generated by Django 4.1.2 on 2023-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0025_alter_qa_interface_level_alter_qa_interface_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='question',
            field=models.TextField(help_text=' &nbsp; <button type="button" class="btn btn-danger btn-sm align-top" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-html="true"  data-bs-content=" Multi-hop questions require systems to aggregate information between multiple contexts, the ability of a system to reason over multiple sources of data such as paragraphs to output desired answer. Here, the system has to reason with information taken from more than one document (i.e. Parapgaphs) to arrive at the final answer. <br> <br> <b> Example: </b> What is the population of the capital city of Bangladesh ? <br> <b>Answer: </b> 40 Millions !!<br> <b>Reasoning:</b> Capital City of Bangladesh ---> Dhaka ---> Population: 40 Millions. <br> <br> Click <a href= https://hotpotqa.github.io/  target=_blank > here </a> to see further details of multihop questions ! "> ? </button>', max_length=1000),
        ),
    ]
