# Generated by Django 4.1.2 on 2023-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0026_alter_qa_interface_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='par_A',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qa_interface',
            name='par_B',
            field=models.CharField(max_length=150),
        ),
    ]
