# Generated by Django 4.1.2 on 2023-03-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0030_qa_interface_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_interface',
            name='author_id',
        ),
    ]
