# Generated by Django 4.1.2 on 2023-03-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0031_remove_qa_interface_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa_interface',
            old_name='par_A_Raw',
            new_name='par_A_mod',
        ),
        migrations.RenameField(
            model_name='qa_interface',
            old_name='par_B_Raw',
            new_name='par_B_mod',
        ),
    ]
