# Generated by Django 4.1.2 on 2023-03-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0032_rename_par_a_raw_qa_interface_par_a_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_interface',
            name='par_A_mod',
        ),
        migrations.RemoveField(
            model_name='qa_interface',
            name='par_B_mod',
        ),
    ]
