# Generated by Django 4.1.2 on 2023-06-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_interface', '0033_remove_qa_interface_par_a_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_interface',
            name='title_A',
            field=models.CharField(max_length=15),
        ),
    ]
